### ISSUE TITLE
Need more clarity on the role of AI in login module

### ISSUE THREAD

**Issue by NiteshDowell** [LL05-AI-Dowell/R05.001.AI.InputModule.Dowell#1]
-Will AI be logging in everyday? If so, will it get different username and password everyday?
-Will AI be a separate program like a bot which will be logging in? 
-Or will AI be always be logged in and monitor what the other evaluators are doing?
-Not clear about the type of logs we should keep

**Comment by thomasgeorgedowell** [comment]
AI is a separate module used everywhere to capture events, so first capture the inputs
