### ISSUE TITLE
Basic input logic

### ISSUE THREAD

**Issue by thomasgeorgedowell** [LL05-AI-Dowell/R05.001.AI.InputModule.Dowell#3]
Start input logic files
1. How Dowell.AI will See
2. How Dowell.AI will Hear
3. How Dowell.AI will Taste
4. How Dowell.AI will Touch
5. How Dowell.AI will Smell

**Comment by thomasgeorgedowell** [comment]
I can't see the file created by @NagarajanDowell 
Share the link

**Comment by thomasgeorgedowell** [comment]
Concept of dowell AI

<img width="557" alt="AI over 5 years" src="https://user-images.githubusercontent.com/68909712/90422593-bad06a00-e0d8-11ea-8ffd-8996546bc6fe.png">
<img width="348" alt="AI concept 2020" src="https://user-images.githubusercontent.com/68909712/90422622-c459d200-e0d8-11ea-9773-fa073b33965f.png">

**Comment by MaryDowell** [comment]
> I can't see the file created by @NagarajanDowell
> Share the link

https://github.com/LL05-AI-Dowell/R05.001.AI.InputModule.Dowell/blob/master/Logic.AI.InputModule.Dowell
